#ifndef _EXPORT_GRAPHICS_GEOMETRY_GEOMETRYDATA_H
#define _EXPORT_GRAPHICS_GEOMETRY_GEOMETRYDATA_H

#ifdef _MSC_VER
    #pragma once
#endif  // _MSC_VER

#endif  // !_EXPORT_GRAPHICS_GEOMETRY_GEOMETRYDATA_H
